FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# RWC demo

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/kathryn]

### List All Questions [GET]

+ Request
    
    + Headers
        
            x-my-custom-header: 10

+ Response 200 (application/json)

        [
            "question_1",
            "question_5"
        ]